name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"

      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        token: ${{ secrets.GITHUB_TOKEN }}
